[package]
name = "peer-stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bgpkit-parser = "0.7.2"
bgpkit-broker = "0.4"
ipnetwork = "0.18.0"

serde = {version="1", features=["derive"]}
serde_json = {version = "1.0", features = ["std"]}

tracing = "0.1"
tracing-subscriber = "0.3.3"

indicatif = "0.15"

rayon = "1.5.1"
structopt = "0.3.26"
bzip2 = "0.4.3"

anyhow = "1.0"
chrono = "0.4.19"

[[bin]]
name = "peer-stats"
path = "src/main.rs"

[[bin]]
name = "peer-stats-bootstrap"
path = "src/bootstrap.rs"
